Создал модуль по генерации карт
nypi/hypernull pull request #3
Opened 2021-12-14 11:09 UTC by AlekseyGoldberg

Привет! Я Жижин Алексей. Я  выполнял задание итогового проекта по генерации карт

2021-12-14 12:44 UTC, nypi commented on CreateMap/pom.xml
> +    <properties>
Мы используем Java 11, версия компилятора прописана в главном pom-файле. Эти строки можно убрать

2021-12-14 12:46 UTC, nypi commented on CreateMap/pom.xml
> +    <artifactId>CreateMap</artifactId>
Название артефакта должно быть без заглавных букв. Используй маленькие буквы и дефисы

2021-12-14 12:47 UTC, nypi commented on CreateMap/src/main/java/CreateMap.java
> +    public CreateMap(int height, int width) {
Не стоит инициализировать статические поля параметрами конструктора

2021-12-14 12:48 UTC, nypi commented on CreateMap/src/main/java/InitSettings.java
> +    public int getView_radius() {
ViewRadius стоит сделать побольше. Посмотри, пож, какие значения используются в текущих картах в директории maps/

2021-12-14 12:49 UTC, nypi commented on CreateMap/src/main/java/InitSettings.java
> +    public int getMining_radius() {
В название метода закралось нижнее подчеркивание, стоит убрать

2021-12-14 12:51 UTC, nypi commented on CreateMap/src/main/java/map/map_2.map
> +map_size 6 10
Это слишком маленькие карты, их стоит сделать покрупнее. Для примерного понимания размеров смотри текущие карты

2021-12-14 12:54 UTC, nypi commented on CreateMap/src/main/java/map/map_2.map
> +map_size 6 10
Также по названия. Выбери, пожалуйста, вместо map_N.map какой-нибудь другой префикс - у нас уже есть набор карт с префиксом map. Можно взять, например, maze_N.map Ну и сгенерируй по две карты на каждое количество ботов. Чтобы их суммарно стало в два раза больше

2021-12-14 12:54 UTC, nypi requested changes
Поправь, пожалуйста, замечания по коммитам

2021-12-15 08:36 UTC, AlekseyGoldberg commented
Изменил все недочеты

2021-12-15 16:57 UTC, merged